config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get    "signup",  to: "devise/registrations#new"
    post   "signup",  to: "devise/registrations#create"
    get    "signin",  to: "devise/sessions#new"
    post   "signin",  to: "devise/sessions#create"
    delete "signout", to: "devise/sessions#destroy"
  end

  resources :green_acts
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    can :read, :all
    return unless user.present?
    can :manage, GreenAct, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/green_act.rb
class GreenAct < ApplicationRecord
  belongs_to :user

  validates_presence_of :content, message: "is required"
  validates_length_of :content, maximum: 280
  validates_length_of :details, maximum: 10_000
end

app/models/user.rb
class User < ApplicationRecord
  has_many :green_acts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name, :username
  validates_length_of :name, :username, in: 2..25
  validates_uniqueness_of :username, case_sensitive: false
  validates_format_of :username,
    with:    /\A[a-zA-Z0-9_\-]+\z/,
    message: "only allows letters, numbers, _ and -"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do
    respond_to do |format|
      format.html do
        if !user_signed_in?
          redirect_to_sign_in_page
        else
          redirect_to_home_page
        end
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up,        keys: [:name, :username]
    devise_parameter_sanitizer.permit :account_update, keys: [:name, :username]
  end

  def redirect_to_sign_in_page
    flash[:warning] = "You must sign in first."
    redirect_to signin_url
  end

  def redirect_to_home_page
    flash[:warning] = "You are not authorize to perform this action."
    redirect_to root_url
  end
end

app/controllers/green_acts_controller.rb
class GreenActsController < ApplicationController
  load_and_authorize_resource

  def new
  end

  def create
    @green_act = current_user.green_acts.build green_act_params
    if @green_act.valid?
      @green_act.save
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @green_act.update green_act_params
      flash[:success] = "Your green act is successfully updated"
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    if @green_act.destroy
      flash[:success] = "Your green act is successfully deleted"
    else
      flash[:error] = "There is an error while trying to delete your green act"
    end
    redirect_to root_url
  end

  private

  def green_act_params
    params.require(:green_act).permit :content, :details
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @green_acts = GreenAct.includes(:user).order created_at: :desc
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title title = ""
    title.empty? ? "Green Acts" : "#{title} | Green Acts"
  end

  def bootstrap_alert_class_for alert_type
    alert_type_mapping = {
      notice: "alert-info",
      alert:  "alert-warning",
      error:  "alert-danger"
    }

    alert_type_mapping.fetch alert_type.to_sym, "alert-#{alert_type}"
  end
end

app/views/green_acts/_form.html.haml
.row.justify-content-center
  .col-sm-6.col-md-4.mt-3
    = form_for @green_act do |f|
      .form-group
        = f.label :content, "Your Green Act"
        = f.text_area :content, class: "form-control"
        = render "shared/form_error_message", object: @green_act, field: "content"

      .form-group
        = f.label :details, "More details (optional)"
        = f.text_area :details, class: "form-control"

      .form-group
        = f.submit "Submit", class: "btn btn-primary"

= render "shared/highlight_error_fields"

app/views/green_acts/_green_act.html.haml
.card.mt-3
  - if can? :manage, green_act
    .card-header
      .btn-group
        = link_to "Edit", edit_green_act_path(green_act), class: "btn btn-sm btn-secondary"
        = link_to "Delete", green_act, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger"
  .card-body
    .card-text #{green_act.content}
    %small.text-muted
      suggested by #{green_act.user.name},
      #{time_ago_in_words green_act.created_at} ago

app/views/green_acts/edit.html.haml
- provide :title, "Edit Green Act"

= render "form"

app/views/green_acts/new.html.haml
- provide :title, "Share your Green Act"

= render "form"

app/views/home/index.html.haml
.row.justify-content-center.mt-3
  .col-md-8.justify-content-center
    = render @green_acts

app/views/layouts/_flash_messages.html.haml
- if flash.any?
  - flash.each do |type, message|
    %div{:class => "mt-3 alert #{bootstrap_alert_class_for type}"}
      = message
      %button.close{:type => "button", "data-dismiss" => "alert"}
        %span &times;

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-sm.navbar-dark.bg-dark
  .container
    %a.navbar-brand{:href => "#"} Green Acts
    %button.navbar-toggler{"data-toggle" => "collapse", "data-target" => "#navigationMenu"}
      %span.navbar-toggler-icon

    .collapse.navbar-collapse#navigationMenu
      %nav.navbar-nav.ml-auto
        - if user_signed_in?
          .nav-item
            = link_to "Share your Green Act", new_green_act_path, class: "nav-link"
          .nav-item.dropdown
            %a.nav-link.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"} Username
            .dropdown-menu
              %a.dropdown-item{:href => "#"} Profile
              = link_to "Account Settings", edit_user_registration_path, class: "dropdown-item"
              .dropdown-divider
              = link_to "Sign Out", signout_path, method: :delete, class: "dropdown-item"
        - else
          .nav-item
            = link_to "Sign Up", signup_path, class: "nav-link"
          .nav-item
            = link_to "Sign In", signin_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = full_title(yield :title)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/nav"
    .container
      = render "layouts/flash_messages"
      = yield

app/views/shared/_form_error_message.html.haml
- if object.errors[field].any?
  .invalid-feedback
    = "#{field.to_s.humanize} #{object.errors[field][0]}"

app/views/shared/_highlight_error_fields.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $(".field_with_errors > *").addClass("is-invalid");
  });
</script>